services:
  db:
    image: mysql
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - todo_network

  backend:
    build: ./todoapp_backend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - todo_network

  frontend:
    build: ./todoapp_frontend
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  db_data:
    driver: local
